### ISSUE TITLE
Shall cargo-geier print some happy character for forbid(unsafe_code) crates?

### ISSUE THREAD

**Issue by vi** [anderejd/cargo-geiger#27]
Instead of a ☢, something positive may be printed.

**Comment by anderejd** [comment]
Sounds nice! Any suggestions?

**Comment by anderejd** [comment]
⭐ ?

**Comment by vi** [comment]
A good choice.

Although it is symmetric and round-ish, which brings it closer to ☢ than to an empty space. Imagine some ASCII-ficator turning both `⭐` and `☢` into a plain `*`.

The character should probably be small (closer to empty space), not central-symmetric (to differ greatly from ☢) and associate with something positive (protection, safety, verifiedness, certitude).

Adding more contenders to the mix (not necessary abiding by all the rules above):

✓ 👍 ☺ 🕶 👑 ⛑ 💎 🐚 🦀 🌰 🍺 ⛰ ⚓ ☂ ✨ 🏆 ♥ 🔒 🛡 💯

**Comment by anderejd** [comment]
Hmm I replied from my Android phone using firefox. On macOS with FF the shield looks kinda weird. I think the lock 🔒 is my pick 😆 ...

**Comment by anderejd** [comment]
They look the same in and out of the code block for me, but smaller inside.

Lets print them in a couple of different terminals and post the screenshots. I just realized that I have no idea how the current rad icon looks on windows... I'll try it on Win 10 later this week.

**Comment by anderejd** [comment]
To begin with, the above candidates in macOS:

<img width="472" alt="screen shot 2018-07-27 at 10 01 14" src="https://user-images.githubusercontent.com/3704611/43309160-4741131e-9184-11e8-992b-1304ba754e04.png">

**Comment by anderejd** [comment]
I would like to push this forward. All crates without forbid(unsafe) should be reported as "unknown" even if the numbers are 0/0 unsafe for every metric. The new "unknown" status could be printed in yellow perhaps, decorated by a question mark.

**Comment by anderejd** [comment]
Fixed by #52
