### ISSUE TITLE
Make it available as a library?

### ISSUE THREAD

**Issue by icefoxen** [anderejd/cargo-geiger#30]
I want to make a website that gives statistics on various crates, including unsafe usage. Naturally I immediately thought of this, but using cargo-geiger to output data and then attempting to re-parse it seems excessively hard. Would you accept a PR that refactors most of the actual work into a library crate?

I don't think I would ever really expect a stable API or such, but being able to keep all the processing in one program would be nice.

**Comment by anderejd** [comment]
Hello, nice to see you again 😄 👍

> Would you accept a PR that refactors most of the actual work into a library crate?

Yes! I think this makes sense for most command line programs as well, to keep the CLI part in the main program and the rest as a library.

> I don't think I would ever really expect a stable API or such, but being able to keep all the processing in one program would be nice.

Yes, let's do the 0.x dance to begin with. Keep it simple and let's do this!

**Comment by anderejd** [comment]
Oh, I just thought of a suggestion. Can we please keep both the CLI and library crate in this git repository? That would make it easier to work with and would make the code more discoverable for newcomers, in my opinion. If you would like to co-maintain I will gladly add you.

**Comment by icefoxen** [comment]
Nice to see you again as well!

And, I was intending to keep it all in one repo, I was going to just move most of `main.rs` into `lib.rs`, and add a `bin/cargo-geiger.rs` with all the command line handling stuff.  Crate fragmentation is one of my pet peeves.  ;-)

I'll gladly help co-maintain, though I'm afraid you shouldn't expect me to do *that* much work on stuff.  I just don't have time to be too dedicated.  In the interests of having a higher bus number for this project though, go ahead.

**Comment by anderejd** [comment]
Excellent, collaborator invite has been sent!
My Rust time is limited at the moment so another minimal-maintainer is 100% better than me alone :)

**Comment by anderejd** [comment]
Do we need to modify the Cargo.toml to allow using only the library part from crates.io or will a new cargo publish be enough?

**Comment by icefoxen** [comment]
You know...  I'm not sure.  I'm pretty sure that just a new publish will be enough though.

**Comment by anderejd** [comment]
I'll prep and publish a new release.

**Comment by anderejd** [comment]
Do you have an example project using the master branch as a library?

While trying to test a minimal example program using cargo-geiger as a library, it seems to me that the cargo executable needs to launch cargo plugins as a subprocess in order to load the correct dynamic libraries. Do you have similar results?

If cargo needs to be the parent process then maybe adding some structured output format would be more useful, like optional json output perhaps?

**Comment by icefoxen** [comment]
> Do you have an example project using the master branch as a library?

Honestly, I haven't tried yet. XD I've had similar issues with libraries while developing though; I need to actually install it and run with `cargo geiger ...` instead of being able to just do `cargo run` in the project dir.

**Comment by anderejd** [comment]
The library ´rust-analyzer´ could become an interesting alternative to the ´rustc´ depedency since ´cargo-geiger´ doesn't need to generate any machine code.

https://github.com/rust-analyzer/rust-analyzer
https://ferrous-systems.com/blog/rust-analyzer-2019/

**Comment by dpc** [comment]
Hi. I'm interested in this for [`cargo-crev`](https://github.com/dpc/crev/tree/master/cargo-crev). In the `cargo crev verify deps` I'd like to display a flag or something for dependencies containing `unsafe` to help users identify crates that need review most.

**Comment by dpc** [comment]
> Would you like to attempt a PR for that or would you prefer that I do it?

I am always tight on time. If you can do it, I'll take it. If you can't, I'll try to get to it at some point. :)

**Comment by anderejd** [comment]
Then I'll try to put in some time for this during the coming week or so. That refactoring has been bugging me for quite a while, guess it's time to just do it 😆

**Comment by anderejd** [comment]
The #41 was just merged and I think that should make cargo-geiger almost usable as a library now, almost. The public API is in very rough shape and I would like some help to polish that.

Do you, @icefoxen and @dpc think the master branch is in good enough shape to start experimenting with using it as a library now?

**Comment by dpc** [comment]
Good enough to me. :)

**Comment by anderejd** [comment]
Cool :) I'm looking forward to see what you make of it.

**Comment by anderejd** [comment]
Sure sounds very reasonable. The only reason I made it private was to start removing things from the public API since the current version unintentionally exposes quite a few implementation details.

I will have more time for this tonight but feel free to make PRs for API changes ;)

> fn find_unsafe seems like the closest thing

Yepp, that's it. I think It needs to be chopped into smaller more focused functions and move the HashSet insertion to the caller. The function should return an `impl Iterator<Item = Something appropriate>` too let the caller build the HashSet. And it should be made public.

https://github.com/anderejd/cargo-geiger/blob/master/src/lib.rs#L301

**Comment by anderejd** [comment]
Okay, ☕️ has been administered.

This comment is a note for myself as much as part of the conversation to sorry for the spam.

`fn find_unsafe` should not care about if a file is used in the build or not. That is a separate concern from scanning and should be handled entirely by the caller. `fn find_unsafe` should return something like `impl Iterator<Item = (source file path, unsafe stats)>`.

**Comment by anderejd** [comment]
> Any chance for one function, that can scan one path? I need to get gieger count per standalone crate, that I already have pin-pointed

Now after #45 I think the cargo-crev use-case could be covered by the public API.

1. Call `find_rs_files_in_package`
1. Use the iterator from step 1 to send file names to `find_unsafe_in_file` 
1. Summarize the stats from step 2 in the caller code

Thoughts?

**Comment by dpc** [comment]
`find_unsafe_in_dir` looks like what I want. :)

While I was looking at it... why so many `unwrap`s and `expect`s? :P

**Comment by anderejd** [comment]
> find_unsafe_in_dir looks like what I want. :)

...I just refactored that into other functions... I can add it back if you'd like? 😆 Were you looking at the latest commit in master?

> While I was looking at it... why so many unwraps and expects? :P

Lack of time 🤷‍♂️  But yes, they should be replaced by Result.

**Comment by anderejd** [comment]
Thanks for the report!

It looks like the time has come to remove the last unwraps and excepts. I can probably find the time to look at it this weekend. Don't be shy to make a PR for this in the meantime :)

**Comment by anderejd** [comment]
@dpc Please take a peek at #49

**Comment by anderejd** [comment]
Merged #48. `find_unsafe_in_file` shouldn't panic now. I haven't looked into why syn return an error yet.

**Comment by dpc** [comment]
I'll try it out at some point. :) Thanks!

**Comment by anderejd** [comment]
The library parts that have been decoupled from the cargo plugin are now released on crates.io: https://crates.io/crates/geiger

I think this issue can be closed now?

**Comment by anderejd** [comment]
Closing, feel free to re-open or create new related issues! 🙂
