### ISSUE TITLE
Incorrect numbers for the resvg crate

### ISSUE THREAD

**Issue by RazrFalcon** [anderejd/cargo-geiger#4]
This app is reporting `(0, 141, 0, 0, 0)` for the [resvg](https://github.com/RazrFalcon/resvg) crate, which has a single `unsafe` and it became available only when the `cairo-backend` feature is set.

**Comment by anderejd** [comment]
Hmm I found this file when using github search for "unsafe" in the repos: 
https://github.com/RazrFalcon/resvg/blob/03c666e0ee40a2cc0e4efaa32ad1ddc0490d3999/capi/src/lib.rs

Looks like roughly 30 unsafe blocks so 141 unsafe expressions seems reasonable, but needs manual verification. Thank you for the report!

**Comment by RazrFalcon** [comment]
It's a separate crate, but it the same workspace.

**Comment by anderejd** [comment]
Ah look at that, then my current implementation is definitely wrong, it sums up all rust unsafe usages under each crate downloaded by cargo. I will need to study the cargo api closer. How would you expect `cargo-geiger` to display the workspaces in this case? I have never used cargo workspaces so that is something I will need to study up on as well.

**Comment by anderejd** [comment]
Added this to the known issues list in the readme.

**Comment by RazrFalcon** [comment]
I think that only the current crate should be processed, ignoring the workspace as a whole. I don't know the details about how workspaces are implemented in the cargo, but you can look at my own [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat), which works with workspaces as expected (at least by me).

>each crate downloaded by cargo

But it will not be downloaded and/or build by default. Only the root one will.

**Comment by anderejd** [comment]
Nice thanks for the cargo-bloat link. It compiles using cargo though, not sure that will work here. I don't find anything in the cargo docs about getting back from cargo what source files were used for the compilation, I could be wrong, only browsed the docs for 5-10 minutes.

The current implementation simply grabs all ".rs" files from dependencies resolved by cargo, that is the reason it is not working correctly for resvg. However, the crate does contain .rs files with unsafe code in them. I will need some time to study the cargo api and or get some help with figuring this out.

Would the proper solution be to make a cargo perform a build and from there try to get cargo to report back what source files were actually used?

**Comment by RazrFalcon** [comment]
>Would the proper solution be to make cargo perform a build and from there try to get cargo to report back what source files were actually used?

The build step is not a problem for me, but I'm not sure that cargo has the required data.

You should ask in the cargo repo itself. That's what [I did](https://github.com/rust-lang/cargo/issues/4927).

**Comment by anderejd** [comment]
Fixed by: #17
