### ISSUE TITLE
Switch to ignore build-dependencies and dev-dependencies

### ISSUE THREAD

**Issue by alexmaco** [anderejd/cargo-geiger#42]
Although ideally build code should be all safe, often build and dev dependencies pull in a lot of other crates containing unsafe. There are generally less useful to examine than the code going into the crate, and it would be useful to be able to ignore them.

Further, i would suggest ignoring build and dev dependencies could be done by default, with the flag being there to add them back into analysis for the cases where you need them.

I propose the flags should be `--all-dependencies | --all-deps`, that would alias `--build-dependencies | -- build-deps` and `--dev-dependencies | --dev-deps`. As the names suggest, these would include all, just the build, or just the dev dependencies, _in addition_ to, and not instead, of the crate and regular dependency code.

**Comment by anderejd** [comment]
Sounds good to me!
