### ISSUE TITLE
Split CLI and library into two crates?

### ISSUE THREAD

**Issue by anderejd** [anderejd/cargo-geiger#49]
While working towards #30 I'm starting to lean towards splitting this crate into two crates. One crate for the CLI app and one crate for the library parts that can be cleanly decoupled from the command line application.

Any ideas or opinions on this?

Some discussion on naming: https://github.com/rust-lang-nursery/cli-wg/issues/87
Related: #30

**Comment by anderejd** [comment]
To me it seems like the obvious choice to keep `cargo-geiger` for the CLI application/cargo plugin. But what would be a good name for the library? `cargo-geiger-lib`? `lib-cargo-geiger`? Something completely different?

**Comment by dpc** [comment]
AFAIK, you can have the same named `bin` and `lib` (eg. `cargo` itself does it). Also, maybe just `geiger`, since it's potentially usable in places other than `cargo` anyway.

**Comment by anderejd** [comment]
> you can have the same named bin and lib

Yes, it seems like it works in the current master, haven't tried publishing that to crates.io yet though. 

The reason I'm thinking of splitting it into two crates is to limit the public API of the library crate, which I can't seem to figure out how to do with modules only, where the cargo-geiger binary needs to access more modules than the library should expose. It's very possible that I'm overthinking this.

**Comment by anderejd** [comment]
Fixed by: #51
