### ISSUE TITLE
Cargo-geiger fails to install due to dependency `structopt = "^0.2.17"`

### ISSUE THREAD

**Issue by Bodup** [anderejd/cargo-geiger#59]
Cargo returns the following error when trying to install cargo-geiger

> cargo install cargo-geiger
 Updating crates.io index
 Installing cargo-geiger v0.7.1
error: failed to compile `cargo-geiger v0.7.1`, intermediate artifacts can be found at `C:\Users\user\AppData\Local\Temp\cargo-installDsbRuJ`
Caused by:
  failed to select a version for the requirement `structopt = "^0.2.17"`
  candidate versions found which didn't match: 0.2.16, 0.2.15, 0.2.14, ...
  location searched: crates.io index
required by package `cargo-geiger v0.7.1`

**Comment by icefoxen** [comment]
Looks like 0.2.17 was yanked on June 2nd, see https://github.com/TeXitoi/structopt/issues/200

**Comment by anderejd** [comment]
Thanks for the report!

That's weird to yank something due to semver rules before publishing a version to replace it. The master branch is ready to publish with updated dependencies, will `cargo publish` when Travis is done.

**Comment by anderejd** [comment]
0.7.2 is published on crates.io.
