### ISSUE TITLE
Why `libc` crate is green?

### ISSUE THREAD

**Issue by ozkriff** [anderejd/cargo-geiger#7]
Because it uses "unsafe" only inside macros?

**Comment by anderejd** [comment]
Good find, thank you! Needs investigation.

**Comment by anderejd** [comment]
Related to: https://github.com/anderejd/cargo-geiger/issues/6

**Comment by anderejd** [comment]
https://stackoverflow.com/questions/28580386/how-do-i-see-the-expanded-macro-code-thats-causing-my-compile-error

**Comment by anderejd** [comment]
Looks like macro expansion requires nightly, source: https://crates.io/crates/cargo-expand

**Comment by anderejd** [comment]
#52 makes libc and similar unsafe usage present as "?" and with the default terminal foreground color. See the changelog for 0.6.0 in the readme.
