### ISSUE TITLE
Some crates counted multiple times for the final tally

### ISSUE THREAD

**Issue by Shnatsel** [anderejd/cargo-geiger#79]
If a crate occurs multiple times in build dependencies, the number of unsafe blocks in it seems to be added multiple times to the final tally.

For example, release 0.11.3 of https://github.com/algesten/ureq totals 2574 unsafe expressions according to cargo-geiger 0.9.0, but that number doesn't align with the individual crate counts. It seems that `ring` with its 480 unsafe expressions is counted multiple times, otherwise there's no way to explain these results.

**Comment by anderejd** [comment]
Thank you for the report! I will try to find some open source time in the coming weeks.

**Comment by anderejd** [comment]
This bug should now be fixed in the latest master.

**Comment by anderejd** [comment]
Released in 0.9.1.
