### ISSUE TITLE
Document unsafe reasons/audit trail

### ISSUE THREAD

**Issue by illustrious-you** [anderejd/cargo-geiger#8]
Consider adding a way to audit uses of unsafe, and output statistics on the audit trail.

One [idea mentioned on the users forum](https://users.rust-lang.org/t/how-not-to-use-unsafe-code/18170/4) is adding audit metadata:

```rust
#[safe(reason = "Bit layout is the same, so safe to transmute")]
unsafe {
    let my_number = mem::transmute::<[u8; 4]; u32>(my_array);
}
```

[I suggested](https://users.rust-lang.org/t/how-not-to-use-unsafe-code/18170/18?u=illustrious-you) this might be supplemented by audit trail tracking, allowing review statistics to be added in cargo:

```rust
#[safe(reason = "Bit layout is the same, so safe to transmute", review="5550")]
unsafe {
    let my_number = mem::transmute::<[u8; 4]; u32>(my_array);
}
```

This was also discussed [on reddit by colindean]([also on reddit](https://www.reddit.com/r/rust/comments/8ssjv2/cargogeiger_yet_another_unsafe_rust_finder/e12dumj/) by considering a macro syntax:

```rust
unsafe_with_reason!(unsafe::reasons::OK_WHATEVER) {
  lolwhat(|wtf| omgbad(wtf)).unwrap()
}
```

`cargo-geiger` is likely the wrong crate to implement the audit trail, but it could be part of a larger "geiger ecosystem". This assumes that a separate toolchain is provided to instrument code with audit metadata.

**Comment by anderejd** [comment]
I’m not going to invest time on this issue but the project is experimental and I like this idea so if someone wants to develop and experiment with this I will gladly merge it, perhaps enabled by a setting or an optional command line flag.

**Comment by anderejd** [comment]
This seems like something for cargo-crev and related to the discussion in #30

**Comment by anderejd** [comment]
After taking quite some time to think this through, I've decided that this is out of scope for this tool. Feel free to continue the discussion here if you'd like or create a new issue.
